/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "on-tertiary-fixed-variant": "#474747",
        "on-tertiary-container": "#848484",
        "on-error-container": "#93000a",
        "surface-container-lowest": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-background": "#1a1b22",
        "on-secondary-fixed": "#1a1c1c",
        "tertiary-fixed": "#e2e2e2",
        "on-secondary": "#ffffff",
        "primary-fixed": "#e2e2e2",
        "outline": "#7e7576",
        "on-secondary-container": "#616363",
        "error-container": "#ffdad6",
        "secondary-container": "#dfe0e0",
        "secondary-fixed": "#e2e2e2",
        "primary-container": "#1b1b1b",
        "tertiary": "#000000",
        "error": "#ba1a1a",
        "surface-tint": "#5e5e5e",
        "on-surface": "#1a1b22",
        "secondary-fixed-dim": "#c6c6c7",
        "tertiary-fixed-dim": "#c6c6c6",
        "on-primary-container": "#848484",
        "secondary": "#5d5f5f",
        "surface-container-low": "#f4f2fd",
        "primary-fixed-dim": "#c6c6c6",
        "surface-container-high": "#e8e7f1",
        "background": "#fbf8ff",
        "on-primary-fixed": "#1b1b1b",
        "on-error": "#ffffff",
        "primary": "#000000",
        "on-primary": "#ffffff",
        "inverse-primary": "#c6c6c6",
        "on-tertiary-fixed": "#1b1b1b",
        "surface-container-highest": "#e3e1ec",
        "on-surface-variant": "#4c4546",
        "inverse-surface": "#2f3038",
        "surface-variant": "#e3e1ec",
        "inverse-on-surface": "#f1effa",
        "outline-variant": "#cfc4c5",
        "surface-dim": "#dad9e3",
        "on-secondary-fixed-variant": "#454747",
        "surface-bright": "#fbf8ff",
        "surface-container": "#eeedf7",
        "tertiary-container": "#1b1b1b",
        "surface": "#fbf8ff",
        "on-primary-fixed-variant": "#474747"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "xl": "128px",
        "xs": "8px",
        "margin-mobile": "20px",
        "lg": "64px",
        "margin-desktop": "64px",
        "md": "32px",
        "base": "4px",
        "sm": "16px",
        "gutter": "24px"
      },
      "fontFamily": {
        "body-lg": ["Inter"],
        "headline-lg": ["Hanken Grotesk"],
        "body-md": ["Inter"],
        "label-caps": ["JetBrains Mono"],
        "headline-md": ["Hanken Grotesk"],
        "headline-lg-mobile": ["Hanken Grotesk"],
        "display": ["Hanken Grotesk"],
        "caption": ["Inter"]
      },
      "fontSize": {
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "headline-lg": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "body-md": ["14px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "label-caps": ["12px", { "lineHeight": "1", "letterSpacing": "0.1em", "fontWeight": "500" }],
        "headline-md": ["20px", { "lineHeight": "1.4", "fontWeight": "500" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "1.2", "fontWeight": "600" }],
        "display": ["64px", { "lineHeight": "1.1", "letterSpacing": "-0.04em", "fontWeight": "600" }],
        "caption": ["12px", { "lineHeight": "1.4", "fontWeight": "400" }]
      }
    }
  },
  plugins: [],
}
